# Generated by Django 4.2.5 on 2023-11-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(default='User', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
