# Generated by Django 4.2.5 on 2023-11-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_users_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='station1',
            name='user_type',
            field=models.CharField(default='Police', max_length=100),
        ),
    ]
