# Generated by Django 4.2.5 on 2023-11-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_station1_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('Hospital_Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Contact_number', models.IntegerField(null=True)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('hospital_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(default='Hospitals', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
