# Generated by Django 4.2.5 on 2023-11-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_user_type_users_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station1',
            old_name='user_type',
            new_name='usertype',
        ),
    ]
