# Generated by Django 4.2.5 on 2023-11-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_user_type_hospitals_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermissingadd',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Age', models.IntegerField(primary_key=True, serialize=False)),
                ('Height', models.CharField(max_length=100)),
                ('Weight', models.CharField(max_length=100)),
                ('Missing_date', models.DateField(max_length=100)),
                ('Missing_place', models.CharField(max_length=100)),
                ('Other_details', models.CharField(max_length=100)),
            ],
        ),
    ]
