# Generated by Django 4.2.5 on 2023-12-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_accident'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accident',
            new_name='Accident1',
        ),
    ]
