# Generated by Django 4.2.5 on 2023-12-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_casesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesheet',
            name='Photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
