# Generated by Django 4.2.5 on 2023-12-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_casesheet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesheet',
            name='Photo',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
