# Generated by Django 4.2.5 on 2023-12-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_casesheet_patient_id_alter_casesheet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesheet',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='casesheet',
            name='Patient_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
