# Generated by Django 4.2.5 on 2023-12-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquirys',
            old_name='hospital_id',
            new_name='hospital',
        ),
    ]
