# Generated by Django 4.2.5 on 2023-12-18 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_hospital_id_enquirys_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirys',
            name='station_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.station1'),
        ),
    ]
