# Generated by Django 4.2.5 on 2023-12-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_enquirys_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirys',
            name='Reply',
            field=models.CharField(default='timezone.now()', max_length=100),
            preserve_default=False,
        ),
    ]
