# Generated by Django 4.2.5 on 2023-12-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_enquirys_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermissingadds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Age', models.IntegerField(null=True)),
                ('Height', models.CharField(max_length=100)),
                ('Weight', models.CharField(max_length=100)),
                ('Missing_date', models.DateField(max_length=100)),
                ('Missing_place', models.CharField(max_length=100)),
                ('Other_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Usermissingadd',
        ),
    ]
