# Generated by Django 4.2.5 on 2023-12-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_usermissingadds_delete_usermissingadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermissingadds',
            name='Pass_to_public',
            field=models.CharField(default='timezone.now()', max_length=100),
            preserve_default=False,
        ),
    ]
