# Generated by Django 4.2.5 on 2023-12-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_usermissingadds_pass_to_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermissingadds',
            name='Pass_to_public',
            field=models.IntegerField(null=True),
        ),
    ]
