# Generated by Django 4.2.5 on 2023-12-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_usermissingadds_pass_to_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident1',
            name='Image',
            field=models.FileField(default='timezone.now()', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
