# Generated by Django 4.2.5 on 2023-12-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_accident1_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accident1',
            new_name='Accidents',
        ),
    ]
