# Generated by Django 4.2.5 on 2023-12-22 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_rename_accident1_accidents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('Enquiry_detail', models.CharField(max_length=100)),
                ('Current_Date', models.DateField()),
                ('Reply', models.CharField(max_length=100)),
                ('enquiry_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.hospitals')),
                ('station_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.station1')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Enquirys',
        ),
    ]
