# Generated by Django 4.2.5 on 2023-12-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_enquiry_delete_enquirys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public_Enquiry',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(max_length=100)),
                ('Enquiry', models.CharField(max_length=100)),
            ],
        ),
    ]
