# Generated by Django 4.2.2 on 2024-01-01 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_public_enquiry_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_enquiry',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.hospitals'),
        ),
    ]
