# Generated by Django 4.2.6 on 2024-01-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_public_enquiry_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_enquiry',
            name='Reply',
            field=models.CharField(default='timezone.now()', max_length=100),
            preserve_default=False,
        ),
    ]
