# Generated by Django 4.2.6 on 2024-01-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_public_enquiry_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missing_found',
            fields=[
                ('missing_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(null=True)),
                ('District', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('Other_details', models.CharField(max_length=100)),
                ('Found_date', models.DateField()),
            ],
        ),
    ]
