# Generated by Django 4.2.5 on 2024-01-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_hospitals_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing_found',
            name='pass_to_police',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.station1'),
        ),
    ]
