# Generated by Django 4.2.6 on 2024-02-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_usermissingadds_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing_found',
            name='Photo',
            field=models.ImageField(default='timezone.now()', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
